# ?????
server.port=8080

# ??SpringBoot?????????????????
server.error.whitelabel.enabled=false

# ??JNDI???JDK11???
# ?????????JVM???
# -Dcom.sun.jndi.rmi.object.trustURLCodebase=true
# -Dcom.sun.jndi.ldap.object.trustURLCodebase=true